name: Update SVG Profile

permissions:
  contents: write
on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests lxml python-dotenv python-dateutil

      - name: Run the updater script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # or use secrets.GITHUB_TOKEN if not using a PAT
          USERNAME: ${{ secrets.USERNAME }}
        run: python main.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add profile.svg
          git commit -m "Update SVG" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
